#!/usr/bin/env python3
"""
Scan extracted_txt/EVs/ per task and build TASK_CONDITION_MAP (task -> list of condition names).
Condition names = .txt file stems (excluding Sync.txt), sorted alphabetically.
Writes the dict to ev_condition_mappings.py for import by dataset.py and test_ev_loading.py.

Usage (from repo root):
  python fm-fmri/build_ev_condition_mappings.py [--ev_root .] [--output fm-fmri/ev_condition_mappings.py]
"""

import argparse
from pathlib import Path
from typing import Dict, List, Set

# Must match dataset.py
TASK_TO_EV_FOLDER: Dict[str, str] = {
    "emotion": "EMOTION",
    "gambling": "GAMBLING",
    "language": "LANGUAGE",
    "motor": "MOTOR",
    "relational": "RELATIONAL",
    "social": "SOCIAL",
    "WM": "WM",
}


def collect_condition_names(ev_root: Path, folder_name: str, max_subjects: int = 10) -> List[str]:
    """
    For a task folder (e.g. EMOTION), collect .txt file stems (excluding Sync.txt) across
    up to max_subjects. Union and sort for consistent order.
    """
    task_ev_base = ev_root / "extracted_txt" / "EVs" / folder_name
    if not task_ev_base.exists():
        return []

    stems: Set[str] = set()
    count = 0
    for item in sorted(task_ev_base.iterdir()):
        if not item.is_dir():
            continue
        if count >= max_subjects:
            break
        for f in item.iterdir():
            if f.is_file() and f.suffix.lower() == ".txt" and f.name.lower() != "sync.txt":
                stems.add(f.stem)
        count += 1

    return sorted(stems)


def main():
    parser = argparse.ArgumentParser(description="Build EV condition name mappings from folder scan")
    parser.add_argument("--ev_root", type=str, default=".", help="Root containing extracted_txt/EVs/")
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Output .py file path (default: ev_condition_mappings.py next to this script)",
    )
    parser.add_argument(
        "--max_subjects",
        type=int,
        default=10,
        help="Max subjects to scan per task to collect condition names (default 10)",
    )
    args = parser.parse_args()

    ev_root = Path(args.ev_root).resolve()
    if not ev_root.exists():
        print(f"Error: ev_root does not exist: {ev_root}")
        return 1

    evs_base = ev_root / "extracted_txt" / "EVs"
    if not evs_base.exists():
        print(f"Error: extracted_txt/EVs not found under {ev_root}")
        return 1

    mapping: Dict[str, List[str]] = {}
    for task_name, folder_name in TASK_TO_EV_FOLDER.items():
        names = collect_condition_names(ev_root, folder_name, max_subjects=args.max_subjects)
        mapping[task_name] = names
        print(f"  {task_name}: {names}")

    out_path = args.output
    if not out_path:
        out_path = Path(__file__).resolve().parent / "ev_condition_mappings.py"
    else:
        out_path = Path(out_path)

    lines = [
        "# Auto-generated by build_ev_condition_mappings.py — do not edit by hand.",
        "# Task -> list of condition names (from .txt file stems, excluding Sync), sorted.",
        "# Condition code 1 = first in list, 2 = second, etc.",
        "",
        "from typing import Dict, List",
        "",
        "TASK_CONDITION_MAP: Dict[str, List[str]] = {",
    ]
    for task_name, cond_list in mapping.items():
        # Escape quotes in condition names
        repr_list = ", ".join(repr(c) for c in cond_list)
        lines.append(f'    "{task_name}": [{repr_list}],')
    lines.append("}")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote: {out_path.resolve()}")
    return 0


if __name__ == "__main__":
    exit(main())
